2022-round-1/parikshit14/nx_tutorial_script.py

completed task forth

---

2022-round-1/Lukong123/nx_tutorial_script.py

Still a newbie, please this script is open to corrections.

tutorial script

---

2022-round-1/unna97/nx_tutorial_script.py

Added the tutorial file for the task mentioned in issue #5

adding the tutorial script unna97/nx_dev_tutorial_script.py

---

2022-round-1/joyceannie/nx_tutorial_script.py

Added networkx tutorial script

Added networkx tutorial script

---

2022-round-1/0ddoes/nx_pull_requests.txt

I have updated the nx_pull_requests.txt file. For further PRs too I will add it in this thread.

Added another PR link

---

2022-round-2/chimaobi-okite/nx_tutorial_script.py

added nx_tutorial_script.py script

task 5 : Read through the NetworkX tutorial and create a python script 

---

2022-round-2/nsengiyumva-wilberforce/nx_pull_requests.txt

This a link to my first PR on [networkx](https://github.com/networkx/networkx) repo

fixed first issue

---

2022-round-2/chimaobi-okite/nx_pull_requests.txt

improved test coverage for algorithms in richclub.py

made a new contribution to networkx

---

2022-round-2/nsengiyumva-wilberforce/nx_pull_requests.txt

documentation fix PR

---

2022-round-2/Qudirah/nx_pull_requests.py.txt

Fix an issue in the NetworkX codebase

---

2022-round-2/hrshshrm/nx_pull_requests.txt

Addition of nx_pull_requests file with links to Outreachy PRs, as per #4

addition of nx_pull_requests file

---

2022-round-2/paulitapb/nx_pull_requests.txt

Added some new PRs and contributions

New PR: Added coverage for clique.py and discovered a bug in swap.py

---

2022-round-2/Qudirah/nx_pull_requests.py.txt

@MridulS please check them out

more pull requests added

---

2023-round-1/Qudirah/nx_tutorial_script.py

nx tutorial script added

---

2023-round-1/mmbogajemimah/nx_pull_requests.txt
2023-round-1/mmbogajemimah/nx_tutorial_script.py

nx_pull_requests.txt

---

2023-round-1/navyagarwal/nx_pull_requests.txt

Added links to all PRs, issues and discussions in nx_pull_requests.txt

Update PR file

---

2023-round-1/devotuoma/nx_tutorial_script.py

I have corrected the codes and created an exploratory notebook and script.

exploratory notebook

---

2023-round-2/khushishikhu/nx_dev_test_output.txt

Setup local development environment

---

2023-round-2/Ytemiloluwa/nx_tutorial_script.py

Read through the NetworkX tutorial and create a python script #5

Read through the NetworkX tutorial and create a python script #5

---

2023-round-2/Tanya-Rawat/nx_tutorial_script.py

Create a python script

---

2023-round-2/khushishikhu/nx_pull_requests.txt
2023-round-2/khushishikhu/nx_tutorial_sctript.py

Khushishikhu patch 4

---

2023-round-2/achluma/nx_pull_requests.txt

Added PR2 task3
